# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f59c9126bef9d41c827d8f2b6abfcc81951fd8f7021230b7e9b287dbd0efc4c263702cd096fa739013034246c4ea1d404174cebd2e845b137a6fd2613fe88f

test:
  secret_key_base: f2899d8f6baf8afbdd78c7433f02ae662801a3551f0bf9e69cc47aaf16ead02023e416575c94c5649772a065342ed87c095a87fc8fb54b74931cfe2bf34b8eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
